<?php


/**
 * Implements hook_menu().
 */
function gf_wallet_menu() {

  $items = array();

  $items['user/%user/wallet'] = array(
    'title'           => 'Wallet',
    'page callback'   => 'gf_wallet_user_wallet_page',
    'page arguments'  => [1],
    'access callback' => '_gf_wallet_user_wallet_page_access',
    'access arguments' => [1],
    // 'type'            => MENU_CALLBACK,
    'type' => MENU_LOCAL_TASK,
    'file'            => 'gf_wallet.pages.inc'
  );

  // $items['gf-wallet/%ctools_js/edit/%user'] = [
  //   'title' => 'Change Production Order Price',
  //   'page arguments' => [1, 3],
  //   'page callback' => 'gf_order_prod_price_edit_js',
  //   'access arguments' => ['gf-order change price'],
  //   'delivery callback' => 'ajax_deliver',
  //   'theme callback' => 'ajax_base_page_theme',
  //   'type' => MENU_NORMAL_ITEM,
  //   'file' => 'gf_order.pages.inc',
  // ];

  return $items;
}


function _gf_wallet_user_wallet_page_access($account){
  global $user;
  return ($user->uid == $account->uid || user_access('access administration pages') || user_access('administer gf-wallet'));
}

/**
 * Implements hook_user_load().
 */
function gf_wallet_user_load($users) {
  $result = db_query('SELECT uid, balance FROM {gf_wallet} WHERE uid IN (:uids)', [
    ':uids' => array_keys($users),
  ]);
  foreach ($result as $record) {
    $users[$record->uid]->wallet['balance'] = $record->balance;
  }
}
