<?php

define('GF_WALLET_CURRENCY_SYMBOL', '¥');


/**
 * Implements hook_menu().
 */
function gf_wallet_menu() {

  $items = array();

  $items['user/%user/wallet'] = array(
    'title'           => 'Wallet',
    'page callback'   => 'gf_wallet_user_wallet_page',
    'page arguments'  => [1],
    'access callback' => '_gf_wallet_user_wallet_page_access',
    'access arguments' => [1],
    'type' => MENU_LOCAL_TASK,
    'file'            => 'gf_wallet.pages.inc'
  );

  $items['gf-wallet/%user/balance-edit'] = array(
    'title' => 'Change The Balance',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['gf_wallet_balance_edit_form', 1],
    'access arguments' => ['administer gf-wallet'],
  );

  // $items['gf-wallet/%ctools_js/balance-edit/%user'] = [
  //   'title' => 'Change Production Order Price',
  //   'page arguments' => [1, 3],
  //   'page callback' => 'gf_order_prod_price_edit_js',
  //   'access arguments' => ['gf-order change price'],
  //   'delivery callback' => 'ajax_deliver',
  //   'theme callback' => 'ajax_base_page_theme',
  //   'type' => MENU_NORMAL_ITEM,
  //   'file' => 'gf_order.pages.inc',
  // ];

  return $items;
}

function gf_wallet_permission() {
  return array(
    'administer gf-wallet' => array(
      'title' => t('Administer gf-wallets'),
      'description' => t('Perform administration a user wallets.'),
    ),
  );
}

function _gf_wallet_user_wallet_page_access($account){
  global $user;
  return ($user->uid == $account->uid || user_access('access administration pages') || user_access('administer gf-wallet'));
}

/**
 * Implements hook_user_load().
 */
function gf_wallet_user_load($users) {
  $records = db_select('gf_wallet', 'w')
    ->fields('w', ['uid', 'balance'])
    ->condition('w.uid', array_keys($users), 'IN')
    ->execute()
    ->fetchAllKeyed();

  foreach ($users as $user) {
    $users[$user->uid]->wallet['balance'] = $records[$user->uid] ?: 0;
  }
}


/**
 * Обновление баланса пользователя.
 *
 */
function _gf_wallet_update_user_balance($uid, $balance=0) {
  global $user;
  // Обновлять разрешаем только имеющим спец. разрешение.
  if (!user_access('administer gf-wallet')) return;

  if ($balance <= 0) {
    db_delete('gf_wallet')
      ->condition('uid', $uid)
      ->execute();
  }
  else {
    db_merge('gf_wallet')
      ->key(array('uid' => $uid))
      ->fields(array(
        'balance' => $balance,
      ))
      ->execute();
  }
}

/**
 * Форма для изменения баланса пользовательского кошелька.
 *
 */
function gf_wallet_balance_edit_form($form, $form_state, $user) {
  $form['#uid'] = $user->uid;
  $form['balance'] = [
    '#type' => 'textfield',
    '#title' => t('Balance'),
    '#description' => t('Change the balance of the wallet for the user !username.',
      ['!username' => l($user->name, 'user/' . $user->uid)]),
    '#element_validate' => ['element_validate_integer'],
    '#default_value' => round($user->wallet['balance']),
  ];
  $form['submit'] = array('#type' => 'submit', '#value' => t('Save'));
  return $form;
}

function gf_wallet_balance_edit_form_submit($form, &$form_state) {
  $balance = $form_state['values']['balance'];
  _gf_wallet_update_user_balance($form['#uid'], $balance);
}

function gf_wallet_preprocess_user_profile(&$variables) {
  $account = $variables['elements']['#account'];
  $button_text = t('The balance of your wallet: !balance !symbol', ['!balance' => $account->wallet['balance'], 
    '!symbol' => GF_WALLET_CURRENCY_SYMBOL]);
  $variables['gf_wallet_balance_button'] = l($button_text, 'user/' . $account->uid . '/wallet',
    array('attributes' => array('class' => array('btn', 'btn-primary')), 'html' => true));

  // $variables['gf_wallet_balance'] = $account->wallet['balance'];
  // $variables['gf_wallet_update_balance_button'] = '';
  // if (user_access('administer gf-wallet')) {
  //   $variables['gf_wallet_update_balance_button'] = l(t('Edit balance'), 'gf-wallet/' . $account->uid . '/balance-edit',
  //     array('attributes' => array('class' => array('wallet-update-balance-btn', 'btn', 'btn-primary')), 'html' => true));
  // }
}
